[global]
nbins = 9
display = False
workers = 2
dataset = boldEso190
outputFolder = ..

[estimate]
Nsurrogates = 99

[DEFAULT]
regions = 

[correction]
nsamples = 0
steps = 200
iters = 50000

; ADD HERE THE INFO FOR SPECIFIC HOSTS
; [dataset name]
; outputFolder = path/to/mat/file/if/not/the/default/one
; workers = # of workers to use

[ndw-workhorse-2]
outputFolder = /mnt/DATA/NonLinearMI/
workers = 12

[NB403303]
outputFolder = ..
workers = 4

; ADD HERE THE INFO FOR NEW DATASETS
; [dataset name]
; filePath = path/to/mat/file/if/not/the/default/one
; fileName = dataset.mat
; fieldName = dictionary key
; healthy_control_start = 64
; healthy_control_end = 0
; A 0 here means "from the beginning" or "until the end"

[MS_fMRI]
filePath = /mnt/DATA/NonLinearMI/
fileName = MS_fMRI.mat
fieldName = MS_fMRI
healthy_control_start = 64
healthy_control_end = 0

[boldEso190]
filePath = /mnt/DATA/NonLinearMI/
fileName = boldEso190.mat
fieldName = subj_tcs
healthy_control_start = 0
healthy_control_end = 90

[ESO190_strin_AAL90]
filePath = /mnt/DATA/NonLinearMI/
fileName = ESO190_strin_AAL90.mat
fieldName = subj_tcs
healthy_control_start = 0
healthy_control_end = 90

[eso245_cra_strin]
filePath = /mnt/DATA/Motion_fMRI/eso245/
fileName = eso245_cra_strin_%(regions)s.mat
fieldName = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[benchmark]
filePath = ..
fileName = eso245_cra_strin_10.mat
fieldName = subj_tcs
healthy_control_start = 0
healthy_control_end = 20

[electrode_BLP]
filePath = /mnt/DATA/NonLinearMI/EEG_el_so_BLP/
fileName = electrode_BLP_band%(regions)s.mat
fieldName = electrode_BLP
healthy_control_start = 0
healthy_control_end = 0

[source_BLP]
filePath = /mnt/DATA/NonLinearMI/EEG_el_so_BLP/
fileName = source_BLP_band%(regions)s.mat
fieldName = source_BLP
healthy_control_start = 0
healthy_control_end = 0

[EEG_bands]
filePath = /mnt/DATA/NonLinearMI/EEG_el_so_BLP/
fileName = EEG_bands_band%(regions)s.mat
fieldName = EEG_bands
healthy_control_start = 0
healthy_control_end = 0


[EEG_bands_sub]
filePath = /mnt/DATA/NonLinearMI/EEG_el_so_BLP/
fileName = EEG_bands_band1_sub.mat
fieldName = EEG_bands
healthy_control_start = 0
healthy_control_end = 0

[iEEG]
filePath = /mnt/DATA/NonLinearMI/iEEG/
fileName = iEEG_part_band%(regions)s.mat
fieldName = EEG
healthy_control_start = 0
healthy_control_end = 0

[iEEG_all]
filePath = /mnt/DATA/NonLinearMI/iEEG/
fileName = iEEG_part.mat
fieldName = EEG
healthy_control_start = 0
healthy_control_end = 0