[global]
bins = 9
display = False
workers = 2
dataset = boldEso190
output_folder = ..
surrogates = 99


[DEFAULT]
dataset_sub = 

[correction]
nsamples = 0
steps = 200
iters = 50000

; ADD HERE THE INFO FOR SPECIFIC HOSTS
; [dataset name]
; output_folder = path/to/mat/file/if/not/the/default/one
; workers = # of workers to use

[ndw-workhorse-2]
output_folder = /home/raffaelli/NonLinearityResultsNew
workers = 20

[NB403303]
output_folder = ..
workers = 7

[giulio-ProBook]
output_folder = ..
workers = 4

; ADD HERE THE INFO FOR NEW DATASETS
; [dataset name]
; file_path = path/to/mat/file/if/not/the/default/one
; file_name = dataset.mat
; field_name = dictionary key
; healthy_control_start = 64
; healthy_control_end = 0
; A 0 here means "from the beginning" or "until the end"

[MS_fMRI]
file_path = /home/raffaelli/NonLinearityData
file_name = MS_fMRI.mat
field_name = MS_fMRI
healthy_control_start = 64
healthy_control_end = 0

[boldEso190]
file_path = /home/raffaelli/NonLinearityData
file_name = boldEso190.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 90

[ESO190_strin_AAL90]
file_path = /home/raffaelli/NonLinearityData
file_name = ESO190_strin_AAL90.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 90

[eso245_cra_strin]
file_path = /mnt/DATA/Motion_fMRI/Datasets/eso245/
file_name = eso245_cra_strin_%(dataset_sub)s.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[benchmark]
file_path = ..
file_name = eso245_cra_strin_10.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 5

[electrode_BLP]
file_path = /home/raffaelli/NonLinearityData/EEG_el_so_BLP/
file_name = electrode_BLP_band%(dataset_sub)s.mat
field_name = electrode_BLP
healthy_control_start = 0
healthy_control_end = 0

[FIX_electrode_BLP]
file_path = /home/raffaelli/NonLinearityData/EEG_el_so_BLP/
file_name = FIX_electrode_BLP_band%(dataset_sub)s.mat
field_name = electrode_BLP
healthy_control_start = 0
healthy_control_end = 0

[source_BLP]
file_path = /home/raffaelli/NonLinearityData/EEG_el_so_BLP/
file_name = source_BLP_band%(dataset_sub)s.mat
field_name = source_BLP
healthy_control_start = 0
healthy_control_end = 0

[FIX_source_BLP]
file_path = /home/raffaelli/NonLinearityData/EEG_el_so_BLP/
file_name = FIX_source_BLP_band%(dataset_sub)s.mat
field_name = source_BLP
healthy_control_start = 0
healthy_control_end = 0

[EEG_bands]
file_path = /home/raffaelli/NonLinearityData/EEG_el_so_BLP/
file_name = EEG_bands_band%(dataset_sub)s.mat
field_name = EEG_bands
healthy_control_start = 0
healthy_control_end = 0


[EEG_bands_sub]
file_path = /home/raffaelli/NonLinearityData/EEG_el_so_BLP/
file_name = EEG_bands_band1_sub.mat
field_name = EEG_bands
healthy_control_start = 0
healthy_control_end = 0

[iEEG]
file_path = /home/raffaelli/NonLinearityData/iEEG/
file_name = iEEG_part_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[iEEG_all]
file_path = /home/raffaelli/NonLinearityData/iEEG/
file_name = iEEG_part.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[eso245_aal]
file_path = /mnt/DATA/Motion_fMRI/Datasets/eso245/
file_name = eso245_aal_%(dataset_sub)s_90.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[movz_aal]
file_path = /mnt/DATA/Motion_fMRI/Datasets/eso245/
file_name = movz_aal_mod_90.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[pat12]
file_path = /home/raffaelli/NonLinearityData/iEEG/
file_name = iEEG_ID12_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[single_voxel]
file_path = /mnt/DATA/Motion_fMRI/Datasets/Weird_manual_masks/eso/
file_name = 100center.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[try_spiking]
file_path = /home/tani/Documents/nonLinear/spikingData
file_name = allen_794812542_rs.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

