[global]
bins = 0
display = False
workers = 2
dataset = boldEso190
output_folder = ..
surrogates = 99


[DEFAULT]
dataset_sub = 

[correction]
nsamples = 0
steps = 200
iters = 50000

; ADD HERE THE INFO FOR SPECIFIC HOSTS
; [dataset name]
; output_folder = path/to/mat/file/if/not/the/default/one
; workers = # of workers to use

[ndw-workhorse-2]
output_folder = /home/raffaelli/NonLinearity/NonLinearityResultsNew
workers = 22

[NB403303]
output_folder = ..
workers = 7

[giulio-ProBook]
output_folder = ..
workers = 4

[dormouse]
output_folder = mnt/DATA/Giulio_NonLinearityResults/ReRun/Results
;/mnt/DATA/Giulio_NonLinearityResults
workers = 44

; ADD HERE THE INFO FOR NEW DATASETS
; [dataset name]
; file_path = path/to/mat/file/if/not/the/default/one
; file_name = dataset.mat
; field_name = dictionary key
; healthy_control_start = 64
; healthy_control_end = 0
; A 0 here means "from the beginning" or "until the end"

[MS_fMRI]
file_path = /home/raffaelli/NonLinearity/NonLinearityData
file_name = MS_fMRI.mat
field_name = MS_fMRI
healthy_control_start = 64
healthy_control_end = 0

[boldEso190]
file_path = /home/raffaelli/NonLinearity/NonLinearityData
file_name = boldEso190.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 90

[ESO190_strin_AAL90]
file_path = /home/raffaelli/NonLinearity/NonLinearityData
file_name = ESO190_strin_AAL90.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 90

[eso245_cra_strin]
file_path = /mnt/DATA/Motion_fMRI/Datasets/eso245/
file_name = eso245_cra_strin_%(dataset_sub)s.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[shaved_eso245_cra_strin]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/shaved_eso245_cra_strin/
file_name = shaved_eso245_cra_strin_%(dataset_sub)s.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[benchmark]
file_path = ..
file_name = eso245_cra_strin_10.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 5

[electrode_BLP]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP/
file_name = electrode_BLP_band%(dataset_sub)s.mat
field_name = electrode_BLP
healthy_control_start = 0
healthy_control_end = 0

[FIX_electrode_BLP]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP/
file_name = FIX_electrode_BLP_band%(dataset_sub)s.mat
field_name = electrode_BLP
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_time_avg1]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedTime_avg1_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_samples_avg1]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedSamples_avg1_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_time_avg2]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedTime_avg2_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_samples_avg2]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedSamples_avg2_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_time_avg4]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedTime_avg4_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_samples_avg4]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedSamples_avg4_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_time_avg1_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedTime_avg1_shadow_band%(dataset_sub)s.mat
field_name = BLP
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_samples_avg1_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedSamples_avg1_shadow_band%(dataset_sub)s.mat
field_name = BLP
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_time_avg2_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedTime_avg2_shadow_band%(dataset_sub)s.mat
field_name = BLP
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_samples_avg2_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedSamples_avg2_shadow_band%(dataset_sub)s.mat
field_name = BLP
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_time_avg4_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedTime_avg4_shadow_band%(dataset_sub)s.mat
field_name = BLP
healthy_control_start = 0
healthy_control_end = 0

[NEW_electrodeBLP_samples_avg4_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_electrodeBLP_fixedSamples_avg4_shadow_band%(dataset_sub)s.mat
field_name = BLP
healthy_control_start = 0
healthy_control_end = 0

[source_BLP]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP/
file_name = source_BLP_band%(dataset_sub)s.mat
field_name = source_BLP
healthy_control_start = 0
healthy_control_end = 0

[FIX_source_BLP]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP/
file_name = FIX_source_BLP_band%(dataset_sub)s.mat
field_name = source_BLP
healthy_control_start = 0
healthy_control_end = 0

[NEW_sourceBLP_time_avg1]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_sourceBLP_fixedTime_avg1_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_sourceBLP_samples_avg1]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_sourceBLP_fixedSamples_avg1_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_sourceBLP_time_avg2]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_sourceBLP_fixedTime_avg2_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_sourceBLP_samples_avg2]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_sourceBLP_fixedSamples_avg2_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_sourceBLP_time_avg4]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_sourceBLP_fixedTime_avg4_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_sourceBLP_samples_avg4]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_sourceBLP_fixedSamples_avg4_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_time_avg1]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedTime_avg1_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_samples_avg1]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedSamples_avg1_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_time_avg2]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedTime_avg2_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_samples_avg2]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedSamples_avg2_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_time_avg4]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedTime_avg4_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_samples_avg4]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedSamples_avg4_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_time_avg1_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedTime_avg1_shadow_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_samples_avg1_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedSamples_avg1_shadow_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_time_avg2_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedTime_avg2_shadow_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_samples_avg2_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedSamples_avg2_shadow_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_time_avg4_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedTime_avg4_shadow_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[PCA_sourceBLP_samples_avg4_shadow]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = PCA_sourceBLP_fixedSamples_avg4_shadow_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[EEG_bands]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP/
file_name = EEG_bands_band%(dataset_sub)s.mat
field_name = EEG_bands
healthy_control_start = 0
healthy_control_end = 0

[trimmed_EEG_bands_time]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = trimmed_EEG_fixedTime_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[FIX_EEG_bands_time]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP/
file_name = FIX_EEG_fixedTime_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[FIX_EEG_bands_samples]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP/
file_name = FIX_EEG_fixedSamples_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_EEG_bands_long]
file_path = /mnt/DATA/EEG_Giulio/
file_name = LONG_EEG_4860Samples_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[OLO_EEG_bands]
file_path = /mnt/DATA/EEG_Giulio/
file_name = OLO_EEG_124s_band_%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_EEG_bands_time]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_EEG_fixedTime_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[NEW_EEG_bands_samples]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP_NEW/
file_name = NEW_EEG_fixedSamples_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0


[EEG_bands_sub]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/EEG_el_so_BLP/
file_name = EEG_bands_band1_sub.mat
field_name = EEG_bands
healthy_control_start = 0
healthy_control_end = 0

[iEEG]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/iEEG/
file_name = iEEG_part_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[iEEG_long]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/iEEG/
file_name = iEEG_band%(dataset_sub)s.mat
field_name = iEEG
healthy_control_start = 0
healthy_control_end = 0

[iEEG_12276]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/iEEG/
file_name = iEEG_12276_band%(dataset_sub)s.mat
field_name = iEEG
healthy_control_start = 0
healthy_control_end = 0

[iEEG_despiked]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/iEEG/
file_name = iEEG_despiked_band%(dataset_sub)s.mat
field_name = iEEG
healthy_control_start = 0
healthy_control_end = 0

[FIX_iEEG_time]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/iEEG/
file_name = FIX_iEEG_fixedTime_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[FIX_iEEG_samples]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/iEEG/
file_name = FIX_iEEG_fixedSamples_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[iEEG_all]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/iEEG/
file_name = iEEG_part.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[lemon_aal]
file_path = /mnt/DATA/LEMON_Giulio/processed/
file_name = lemon_aal_strin_90_ses-0%(dataset_sub)s.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[eso245_aal]
file_path = /mnt/DATA/Motion_fMRI/Datasets/eso245/
file_name = eso245_aal_%(dataset_sub)s_90.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[eso245_aal_filt]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/
file_name = eso245_aal_raw_90_filtered.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[eso245_aal_synth]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/
file_name = eso245_aal_raw_90_synthetic.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[movz_aal]
file_path = /mnt/DATA/Motion_fMRI/Datasets/eso245/
file_name = movz_aal_mod_90.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[pat12]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/iEEG/
file_name = iEEG_ID12_band%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[single_voxel]
file_path = /mnt/DATA/Motion_fMRI/Datasets/Weird_manual_masks/eso/
file_name = 100center.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[shaved_single_voxel]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/
file_name = shaved_100center.mat
field_name = subj_tcs
healthy_control_start = 0
healthy_control_end = 0

[try_spiking]
file_path = /home/tani/Documents/nonLinear/spikingData
file_name = allen_794812542_rs.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_766640955]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_766640955_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_767871931]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_767871931_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_768515987]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_768515987_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_771160300]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_771160300_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_778240327]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_778240327_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_778998620]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_778998620_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_779839471]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_779839471_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_781842082]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_781842082_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_786091066]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_786091066_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_793224716]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_793224716_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_794812542]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_794812542_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_816200189]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_816200189_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_831882777]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_831882777_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_839068429]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_839068429_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_840012044]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_840012044_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[spiking_847657808]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/spiking
file_name = spiking_847657808_%(dataset_sub)s.mat
field_name = spikes
healthy_control_start = 0
healthy_control_end = 0

[standaSym_source]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/StandaSim/eeg_fmri_model_sim_data/
file_name = standaSym_sourceEEG_band_%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[standaSym_scalp]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/StandaSim/eeg_fmri_model_sim_data/
file_name = standaSym_scalpEEG_band_%(dataset_sub)s.mat
field_name = EEG
healthy_control_start = 0
healthy_control_end = 0

[standaSym_BOLD]
file_path = /home/raffaelli/NonLinearity/NonLinearityData/StandaSim/eeg_fmri_model_sim_data/
file_name = standaSym_BOLD.mat
field_name = BOLD
healthy_control_start = 0
healthy_control_end = 0
