[global]
bins = 0
display = False
workers = 2
dataset = the_one_I_always_use
output_folder = ..
surrogates = 99


[DEFAULT]
dataset_sub = 

[correction]
nsamples = 0
steps = 200
iters = 50000

; ADD HERE THE INFO FOR SPECIFIC HOSTS
; [dataset name]
; output_folder = path/to/mat/file/if/not/the/default/one
; workers = # of workers to use

[my-powerful-workstation]
output_folder = /path/to/storage/
workers = 50

[my-laptop]
output_folder = /path/to/storage
workers = 4

; ADD HERE THE INFO FOR NEW DATASETS
; [dataset name]
; file_path = path/to/mat/file/if/not/the/default/one
; file_name = dataset.mat
; field_name = dictionary key
; healthy_control_start = 64
; healthy_control_end = 0
; A 0 here means "from the beginning" or "until the end"

[the_one_I_always_use]
file_path = /path/to/data
file_name = my_data.mat
field_name = name_of_matlab_variable
healthy_control_start = 64
healthy_control_end = 0

[some_other_dataset]
file_path = /path/to/data
file_name = more_data.mat
field_name = another_name_of_matlab_variable
healthy_control_start = 0
healthy_control_end = 90
