[global]
nbins = 9
display = False
workers = 12

[estimate]
Nsurrogates = 99

[dataset]
filePath = ../
; fileName = MS_fMRI.mat
; fieldName = MS_fMRI
; healthy_control_start = 64
; healthy_control_end = 0
fileName = boldEso190.mat
fieldName = subj_tcs
healthy_control_start = 0
healthy_control_end = 90

[correction]
nsamples = 0
steps = 200
iters = 50000