[global]
nbins = 8
display = False

[estimate]
Nsurrogates = 99

[dataset]
filePath = ../
fileName = MS_fMRI.mat
fieldName = MS_fMRI
; fileName = boldEso190.mat
; fieldName = subj_tcs
healthy_control_start = 64
healthy_control_end = 0

[correction]
nsamples = 0
steps = 200
iters = 50000